// Дата останнього змістовного коміту статичних сторінок. Оновлювати вручну,
// коли змінюється текст сторінок поза /calcs.
export const SITE_CONTENT_LASTMOD = '2026-08-29';

export const routeSitemap = [
  '',
  '/calcs',
  '/calcs/imt-calculator',
  '/calcs/fat-calculator',
  '/calcs/calories-calculator',
  '/learn',
  '/learn/intro',
  '/learn/training',
  '/learn/training/warm-up',
  '/learn/training/basic-exercises',
  '/learn/training/load-progression',
  '/learn/nutrition',
  '/learn/nutrition/basics',
  '/learn/nutrition/before-after-training',
  '/learn/nutrition/diet-for-weight-lost',
  '/learn/nutrition/diet-for-gaining-weight',
  '/learn/recover',
  '/learn/recover/enough-rest',
  '/learn/recover/overtraining',
  '/learn/motivation',
  '/learn/motivation/timidity',
  '/learn/motivation/finding-motivation',
  '/learn/motivation/power-of-discipline',
  '/services',
  '/contacts',
  '/blog',
];
